Update genJar.yml

diff --git a/.github/workflows/genJar.yml b/.github/workflows/genJar.yml
--- a/.github/workflows/genJar.yml
+++ b/.github/workflows/genJar.yml
@@ -7,12 +7,12 @@ jobs:
     runs-on: windows-latest
 
     steps:
-      - uses: actions/checkout@v2.4.0
+      - uses: actions/checkout@v2.4.0  # 使用具体版本以提高稳定性
 
-      - name: Set up JDK
-        uses: actions/setup-java@v2.4.0
+      - name: Set up JDK 21
+        uses: actions/setup-java@v2.4.0  # 使用具体版本以提高稳定性
         with:
-          java-version: '17'  # 更改为 Java 17
+          java-version: '21'
           distribution: 'adopt'
           cache: gradle
 
@@ -20,17 +20,11 @@ jobs:
         run: ./build.bat ec
 
       - name: Check if JAR exists
-        id: check_jar
         run: |
-          if (-Not (Test-Path "./jar/custom_spider.jar")) {
-              Write-Host "JAR file not found!"
-              exit 1
-          }
-
-      - name: Skip error and continue
-        if: steps.check_jar.outcome == 'failure'
-        run: |
-          Write-Host "Skipping error in JAR check, continuing with the workflow."
+          if not exist "./jar/custom_spider.jar" (
+            echo "JAR file not found!"
+            exit 1
+          )
 
       - name: Update spider jar
         uses: EndBug/add-and-commit@v7
